### PR TITLE
Added DHCPv6 support

### PR DESCRIPTION
**Pull request by desnoe**
This adds support for DHCPv6. This patch is made of :
- one new file to dissect DHCPv6 packets (dhcp6.py)
- and a modification in existing file udp.py to match DHCPv6 packets on standard ports

### CODE REVIEW

**Comment by iwaseyusuke** [comment]
Great!
It looks very nice to me.

But, according to [CONTRIBUTING.rst](https://github.com/osrg/ryu/blob/master/CONTRIBUTING.rst#submitting-a-change), Ryu project does not use Pull Request on GitHub.
Could you send your patches to ryu-devel@lists.sourceforge.net?

BTW, dhcp6.py has pep8 warning?
It seems to cxceed the max line length of 79 characters...

**Comment by desnoe** [comment]
Thanks. You're right, I'll fix it and run it against PEP8. Then post the patch on the devel list.

**Comment by iwaseyusuke** [comment]
Thanks! We are waiting for your post!

**Comment by anarkiwi** [comment]
Closing as past 12 months old. Please open a new PR if required.

**Pull request closed without merging**
