### PR TITLE
BGP: added method to windraw an advertised prefix via JsonRPC (prefix…

### PR DESCRIPTION
**Pull request by galkindmitrii**
Hello,

This patch allows to delete advertised prefix via json rpc.

Please comment if any more changes are needed.

### CODE REVIEW

**Comment by iwaseyusuke** [comment]
Hi @galkindmitrii 

It looks good to me!
Thank you for posting your PR!

But, Ryu development team does not use Pull Request on GitHub.
We are using `"git format-patch"` style patch to discuss on [ryu-devel mailing list](https://lists.sourceforge.net/lists/listinfo/ryu-devel)
Would you mind sending your patch to this mailing list?
```
$ git format-patch HEAD~N
$ git send-email --to="ryu-devel@lists.sourceforge.net" *.patch
```

**Comment by iwaseyusuke** [comment]
FYI:
`ryu/services/protocols/bgp/application.py` provides more programmable RPC APIs and `"ryu rpc-cli"` is useful for calling these APIs.
(Currently, not documented enough though...)

Example:
```
# Start Ryu-BGP application
$ ryu-manager --bgp-app-config-file ryu/services/protocols/bgp/bgp_sample_conf.py ryu/services/protocols/bgp/application.py
...

# Open Ryu-BGP RPC CLI command prompt
$ ryu rpc-cli --peers=bgp=localhost:50002
(Cmd)
...

# Add a prefix
(Cmd) request bgp network.add [{"prefix": "10.20.1.0/24"}]

# Delete a prefix
(Cmd) request bgp network.del [{"prefix": "10.20.1.0/24"}]
```

**Comment by galkindmitrii** [comment]
Hi @iwaseyusuke 

I see, thanks for your response. That's exactly what I was looking for.
I'll send the patch on the dev list than.

Best regards,

**Comment by anarkiwi** [comment]
Closing as past 12 months old. Please open a new PR if required.

**Pull request closed without merging**
