### PR TITLE
Shortest path forwarding

### PR DESCRIPTION
**Pull request by castroflavio**
I created a shortest path forwarding application using networkX and would like to share it.

### CODE REVIEW

**Comment by TakeshiTseng** [comment]
Hi
Have you test it with pep8?
Please check the coding style with pep8 before you send this patch.
Also, please send patch file to mailing list.
To create patch file, please follow ryubook : http://osrg.github.io/ryu-book/en/html/contribute.html#sending-a-patch

**Comment by rewtelize** [comment]
Hello,

I'm having some loops in my topology and I was looking for a solution. I thought in implementing STP but I only find solutions for Openflow v1.3. Do you think your shortest_path.py can help me?

**Comment by erfanw** [comment]
line 106: in _packet_in_handler
    self.net.add_edge(dpid,src,{'port':msg.in_port})
TypeError: add_edge() takes 3 positional arguments but 4 were given

**Comment by anarkiwi** [comment]
Closing as past 12 months old. Please open a new PR if required.

**Pull request closed without merging**
