### PR TITLE
Update TCP. Insert Payload

### PR DESCRIPTION
**Pull request by ramoncordeiro**
I cannot insert Payload data in TCP PACKET. This is only a suggestion.

I've search on everywhere and no not find a way to Add Payload to Packet TCP in RYU. IF you has a way, please help me

### CODE REVIEW

**Comment by iwaseyusuke** [comment]
Hi @ramoncordeiro 

You can put the payload using `Packet.add_protocol()` as the following.
```python
pkt = packet.Packet()
pkt.add_protocol(ethernet.ethernet(ethertype=...,
                                   dst=...,
                                   src=...))
pkt.add_protocol(ipv4.ipv4(dst=...,
                           src=...,
                           proto=...))
pkt.add_protocol(tcp.tcp(src_port=...,
                           dst_port=...))
payload_data = b'\x00\x00...'  # as a raw binary
pkt.add_protocol(payload_data)
pkt.serialize()
bin_packet = pkt.data
```
Could you try this?

Also, Ryu project does not use PR, would you mind sending to ryu-devel@lists.sourceforge.net if you have some patches?
https://github.com/osrg/ryu/blob/master/CONTRIBUTING.rst#submitting-a-change

**Comment by ramoncordeiro** [comment]
i've done it before. But Does not work for me.  This way is a few complex, others SDN Controllers has forms more simple to do it.

**Comment by iwaseyusuke** [comment]
Hmmm...

First, the current implementation works enough for me. Please try the following script on your environment.
```python
from ryu.utils import binary_str
from ryu.lib.packet import packet
from ryu.lib.packet import in_proto
from ryu.lib.packet import ethernet
from ryu.lib.packet import ipv4
from ryu.lib.packet import tcp

pkt_in = packet.Packet()
pkt_in.add_protocol(
    ethernet.ethernet(
        dst='11:22:33:44:55:66',
        src='aa:bb:cc:dd:ee:ff',
    ),
)
pkt_in.add_protocol(
    ipv4.ipv4(
        dst='10.0.0.1',
        src='10.0.0.2',
        proto=in_proto.IPPROTO_TCP,
    ),
)
pkt_in.add_protocol(
    tcp.tcp(
        src_port=50080,
        dst_port=80,
    ),
)
payload_data = b'arbitrary'  # as a raw binary
pkt_in.add_protocol(payload_data)
pkt_in.serialize()

print('*** constructed packet')
print(pkt_in)

print('*** binary of constructed packet')
print(binary_str(pkt_in.data))

print('*** parsed packet')
pkt_out = packet.Packet(pkt_in.data)
print(pkt_out)

print('*** get payload of TCP')
print(pkt_out.protocols[-1])
```

```bash
$ python test_lib_packet.py
*** constructed packet
ethernet(dst='11:22:33:44:55:66',ethertype=2048,src='aa:bb:cc:dd:ee:ff'), ipv4(csum=42948,dst='10.0.0.1',flags=0,header_length=5,identification=0,offset=0,option=None,proto=6,src='10.0.0.2',tos=0,total_length=49,ttl=255,version=4), tcp(ack=0,bits=0,csum=50471,dst_port=80,offset=5,option=None,seq=0,src_port=50080,urgent=0,window_size=0), b'arbitrary'
*** binary of constructed packet
\x11\x22\x33\x44\x55\x66\xaa\xbb\xcc\xdd\xee\xff\x08\x00\x45\x00\x00\x31\x00\x00\x00\x00\xff\x06\xa7\xc4\x0a\x00\x00\x02\x0a\x00\x00\x01\xc3\xa0\x00\x50\x00\x00\x00\x00\x00\x00\x00\x00\x50\x00\x00\x00\xc5\x27\x00\x00\x61\x72\x62\x69\x74\x72\x61\x72\x79
*** parsed packet
ethernet(dst='11:22:33:44:55:66',ethertype=2048,src='aa:bb:cc:dd:ee:ff'), ipv4(csum=42948,dst='10.0.0.1',flags=0,header_length=5,identification=0,offset=0,option=None,proto=6,src='10.0.0.2',tos=0,total_length=49,ttl=255,version=4), tcp(ack=0,bits=0,csum=50471,dst_port=80,offset=5,option=None,seq=0,src_port=50080,urgent=0,window_size=0), bytearray(b'arbitrary')
*** get payload of TCP
bytearray(b'arbitrary')
```

If this script does not work as expected, it is a bug of the current implementation and we need to fix it.
But it works well, I guess it is not complicated to get the payload of TCP even if compared with adding `payload` attribute to `tcp.tcp` class.

Also if we add `payload` attribute to `tcp.tcp` class, the payload data is duplicated (e.g., `pkt_tcp.payload` and `pkt.protocols[-1]`)? And the same modifications are need to `udp.udp` and other packet classes?

**Comment by anarkiwi** [comment]
Closing as past 12 months old. Please open a new PR if required.

**Pull request closed without merging**
